### ISSUE TITLE
Filtercode plugin not working on image link at Moodle 4.2.2 frontpage 

### ISSUE THREAD

**Issue by juanfortuna** [hribeir0/moodle-theme_stream#2]
Hello, 

I reported an issue for the FilterCode plugin (https://github.com/michael-milette/moodle-filter_filtercodes/issues/268), and I had this answer from Michael Milette. He told me to contact you to report this behavior. 

I am using Moodle 4.2 and I installed the Stream theme in its latest version. I also have the FilterCode plugin installed. In a carousel image of the main page, I want to add a link to another page with a user parameter, the city, but it doesn't work. I have tried everything but I can't get the parameter to pass, it doesn't recognize {city}, and the parameter doesn't load correctly. On other pages within Moodle I have not had problems. I appreciate the help you can give me.

And I got this answer:
_Hi @juanfortuna ,
Thanks for taking the time to report this issue. However, since the {city} tag works elsewhere on your site, I am pretty sure that this is not an issue with FilterCodes but with the theme.
Stream is a great looking theme but, in this instance, it is outputing content without passing it through Moodle filters first.
My recommendation would be to contact Hugo, the developer of the Stream theme and ask him to kindly fix the issue by passing the output through the format_string() or format_text() functions. From what I can see, he is already familiar with FilterCodes so he will likely know what you are talking about. You can report the issue by going to:
https://github.com/hribeir0/moodle-theme_stream/issues
By the way, this issue doesn't just affect FilterCodes. It would also be a problem for those with sites that need to pass text through multi-language filters so I think it is important to get this fixed.

Hope you find this helpful.
Best regards,
Michael Milette_

Maybe you can help me, and if I can help with something please let me know.
Regards, 
Juan.

**Comment by hribeir0** [comment]
Hi Juan,
Thank you very much. Michael is spot on and this is an easy fix.

I expect to push changes later in the day.

**Comment by juanfortuna** [comment]
Thank you very much for the answer!!  I love this theme so, great news hearing that is an easy fix!

**Comment by juanfortuna** [comment]
Let me ask you if you don't mind to let me know when ever you push changes and what I have to do to apply them in my server. 
Thank you very much!

**Comment by hribeir0** [comment]
Fixed by 0a0c6dcee1fc2c825391a72b3d1b075c07267d0e Version 1.2.1

I will now publish on moodle.org/plugins

@juanfortuna you may now pull the new version. Is your site available? Would very much like to take a look and check how you are using the theme. Feel free to send me a DM if you prefer.

**Comment by juanfortuna** [comment]
Hi! thank you very much. Of course mi site is actually on http://campus.valordisa.com.uy/moodle (configuring certificates actually) .  You know, I  downloaded and install the plugin and I want to ask if I install or just override the files that just changed? I will lose any configuration? 
Thank you very much.

**Comment by hribeir0** [comment]
Thank you. Looking good. I Will try to add more widgets in the future.
Probably, it's easier to replace all the stream folder. The settings are saved in the database.  You should have backups however.
I'm unable to test everything

**Comment by juanfortuna** [comment]
Thank you for your time! It's ok I'll install it today! Thanks for all you do!

**Comment by juanfortuna** [comment]
I'm trying to install and when I activate de FilterCode plugin it all goes to a white screen and nothing else to do!. I don't know if you need some extra information. I install a Moodle 4.2.2+ (last stable) download the Stream Theme and FilterCode plugin. When I activate the FilterCode plugin, I can't do nothing else. Thank you.

**Comment by hribeir0** [comment]
I doubt it is related to the theme or the filter plugin. You should enable debug and check if you are using php minimum version.
You also seem to be having issues because of the https certificate
The best place to ask for help about those issues is moodle.org forums

**Comment by michael-milette** [comment]
Hi @hribeir0 and @juanfortuna ,

The white screen issue has been resolved with the latest version of FilterCodes available at https://github.com/michael-milette/moodle-filter_filtercodes/issues/271.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
By the way, nice theme @hribeir0 !

**Comment by hribeir0** [comment]
Thank you very much @michael-milette ! It means a lot coming from you. 
And thank you also for your hard work on the Moodleverse.
