### ISSUE TITLE
Error | Quiz creation using Stream theme

### ISSUE THREAD

**Issue by ted-barao** [hribeir0/moodle-theme_stream#5]
When trying to create a questionnaire, it gives an error:

**Exception - Class "mod_quiz\output\renderer" not found link**
**https://docs.moodle.org/all/pt_br/error/moodle/generalexceptionmessage**

![Screenshot_1](https://github.com/hribeir0/moodle-theme_stream/assets/146985823/8f99a9f7-c793-4009-be45-f0c90dc32ddb)

When forcing the theme in the course, example the theme: Classic, the created form works correctly.

**Versão Moodle**: Version 4.1.6+ (Build: 20231027)
**Theme:** Stream Version 1.2.2 (Build: 2023100400)
**Download link:** https://moodle.org/plugins/theme_stream/1.2.2/30065

**PHP Version:** 8.1.25
**Database version:** mssql (SQLSRVMD-HML) 16.00.4065

**Comment by hribeir0** [comment]
Thank you for your reporting.  I'll try to look into this over the weekend.
Are you able to add and take quizzes?
----------------------------------------------------------------------------------
Obrigado pelo comentário, Vou tentar olhar para isso no fim  de semana.
Consegue adicionar testes? (ou por acaso você se refere À ferramenta de quiz? É que também existe uma ferramente chamada questionnaire)

**Comment by ted-barao** [comment]
Hello, That's right, it's the quiz tool. When using other tools, there apparently was no error.

What type of tests?

**Comment by hribeir0** [comment]
nevermind. Just a mix up with the tool name. I'll try to take a look over the weekend

**Comment by ted-barao** [comment]
No problem.

Thank you for your readiness.

Good week.

**Comment by hribeir0** [comment]
This should fix it 1e21916e04b6cbf78e0a37f126e0fab1a8124cfe

Also available in the plugins page:  https://moodle.org/plugins/theme_stream/1.2.3/30696

**Comment by ted-barao** [comment]
Hi.

Do I need to update the plugin? Does it still display the message?

Or copy the section where it was corrected?

**Comment by ted-barao** [comment]
> Isso deve resolver o problema [1e21916](https://github.com/hribeir0/moodle-theme_stream/commit/1e21916e04b6cbf78e0a37f126e0fab1a8124cfe)
> 
> Também disponível na página de plug-ins: https://moodle.org/plugins/theme_stream/1.2.3/30696


Hi.

Do I need to update the plugin? Does it still display the message?

Or copy the section where it was corrected?

**Comment by hribeir0** [comment]
Yes, please update it if you are running Moodle 4.1. If you are using git to manage it switch to branch MOODLE_STABLE_401 or if you installing from moodle.org download https://moodle.org/plugins/theme_stream/1.2.3/30696

**Comment by ted-barao** [comment]
> Sim, atualize-o se você estiver executando o Moodle 4.1. Se você estiver usando o git para gerenciá-lo, mude para o branch MOODLE_STABLE_401 ou se estiver instalando no moodle.org, baixe https://moodle.org/plugins/theme_stream/1.2.3/30696

Great. Thank you for your attention and agility.
